services:
    nginx:
        image: nginx:1.25.3
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/
        depends_on:
            php:
                condition: service_healthy
        networks:
            - app-network

    php:
        build:
            context: ./docker/php
            args:
                - PHP_VERSION=${PHP_VERSION}
        volumes:
            - ./src:/var/www/
        healthcheck:
            test: ["CMD", "php-fpm", "-t"]
            interval: 10s
            timeout: 5s
            retries: 3
        networks:
            - app-network

    mysql:
        image: mysql:8.3.0
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        command:
            mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 3
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.2.1
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=laravel_user
            - PMA_PASSWORD=laravel_pass
        depends_on:
            mysql:
                condition: service_healthy
        ports:
            - "8080:80"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge